USE QLKS;
GO
--CREATE PROC CHECK_PD(@DATE1 DATE, @DATE2 DATE)
--AS
--	BEGIN
--		SELECT PD.*, TENNV, TENKH, TENP FROM PHIEUDAT PD
--		INNER JOIN KHACHHANG KH ON KH.MAKH = PD.MAKH
--		INNER JOIN NHANVIEN NV ON KH.MAKH = PD.MAKH
--		INNER JOIN CHITIETPHIEUDAT CT ON CT.MAPD = PD.MAPD
--		INNER JOIN PHONG P ON P.MAP = CT.MAP
--		WHERE NGAYDAT BETWEEN @DATE1 AND @DATE2
--		END

CREATE FUNCTION TABLE_THONGTIN(@TEN NVARCHAR(20))
RETURNS TABLE
AS
	BEGIN
		RETURN(
		SELECT KH.*, MAPD FROM KHACHHANG KH
		INNER JOIN PHIEUDAT PD ON PD.MAKH = KH.MAKH
		WHERE TENKH = @TEN)
	END